import type { ChecklistRowDef } from "@/lib/types";

export const ch3Rows: ChecklistRowDef[] = [
  { id: "301", code: "301", title: "Scope", isMainSection: true },
  { id: "301.1", code: "301.1", title: "General.", isMainSection: false },

  { id: "302", code: "302", title: "Occupancy Classification and Use Designation", isMainSection: true },
  { id: "302.1", code: "302.1", title: "Occupancy Classification.", isMainSection: false },
  { id: "302.2", code: "302.2", title: "Use Designation.", isMainSection: false },

  { id: "303", code: "303", title: "Assembly Group A", isMainSection: true },
  { id: "303.1", code: "303.1", title: "Assembly Group A.", isMainSection: false },
  { id: "303.1.1", code: "303.1.1", title: "Small Buildings and Tenant Spaces.", isMainSection: false },
  { id: "303.1.2", code: "303.1.2", title: "Small Assembly Spaces.", isMainSection: false },
  { id: "303.1.3", code: "303.1.3", title: "Associated with Group E Occupancies.", isMainSection: false },
  { id: "303.1.4", code: "303.1.4", title: "Accessory to Places of Religious Worship.", isMainSection: false },
  { id: "303.1.5", code: "303.1.5", title: "Special Amusement Areas.", isMainSection: false },
  { id: "303.2", code: "303.2", title: "Assembly Group A-1.", isMainSection: false },
  { id: "303.3", code: "303.3", title: "Assembly Group A-2.", isMainSection: false },
  { id: "303.4", code: "303.4", title: "Assembly Group A-3.", isMainSection: false },
  { id: "303.5", code: "303.5", title: "Assembly Group A-4.", isMainSection: false },
  { id: "303.6", code: "303.6", title: "Assembly Group A-5.", isMainSection: false },

  { id: "304", code: "304", title: "Business Group B", isMainSection: true },
  { id: "304.1", code: "304.1", title: "Business Group B.", isMainSection: false },
  { id: "304.2", code: "304.2", title: "Airport Traffic Control Towers.", isMainSection: false },
  { id: "304.3", code: "304.3", title: "Ambulatory Care Facilities.", isMainSection: false },
  { id: "304.4", code: "304.4", title: "Higher Education Laboratories.", isMainSection: false },

  { id: "305", code: "305", title: "Educational Group E", isMainSection: true },
  { id: "305.1", code: "305.1", title: "Educational Group E.", isMainSection: false },
  { id: "305.1.1", code: "305.1.1", title: "Accessory to Places of Religious Worship.", isMainSection: false },
  { id: "305.2", code: "305.2", title: "Group E, Day Care Facilities.", isMainSection: false },
  { id: "305.2.1", code: "305.2.1", title: "Within Places of Religious Worship.", isMainSection: false },
  { id: "305.2.2", code: "305.2.2", title: "Five or Fewer Children.", isMainSection: false },
  { id: "305.2.3", code: "305.2.3", title: "Five or Fewer Children in a Dwelling Unit.", isMainSection: false },
  { id: "305.3", code: "305.3", title: "Storm Shelters in Group E Occupancies.", isMainSection: false },

  { id: "306", code: "306", title: "Factory Group F", isMainSection: true },
  { id: "306.1", code: "306.1", title: "Factory Industrial Group F.", isMainSection: false },
  { id: "306.2", code: "306.2", title: "Moderate-Hazard Factory Industrial, Group F-1.", isMainSection: false },
  { id: "306.2.1", code: "306.2.1", title: "Aircraft Manufacturing Facilities.", isMainSection: false },
  { id: "306.3", code: "306.3", title: "Low-Hazard Factory Industrial, Group F-2.", isMainSection: false },

  { id: "307", code: "307", title: "High-Hazard Group H", isMainSection: true },
  { id: "307.1", code: "307.1", title: "High-Hazard Group H.", isMainSection: false },
  { id: "307.1.1", code: "307.1.1", title: "Occupancy Exemptions.", isMainSection: false },
  { id: "307.2", code: "307.2", title: "Hazardous Materials.", isMainSection: false },
  { id: "307.3", code: "307.3", title: "High-Hazard Group H-1.", isMainSection: false },
  { id: "307.3.1", code: "307.3.1", title: "Occupancies Containing Explosives, not H-1.", isMainSection: false },
  { id: "307.4", code: "307.4", title: "High-Hazard Group H-2.", isMainSection: false },
  { id: "307.5", code: "307.5", title: "High-Hazard Group H-3.", isMainSection: false },
  { id: "307.6", code: "307.6", title: "High-Hazard Group H-4.", isMainSection: false },
  { id: "307.7", code: "307.7", title: "High-Hazard Group H-5.", isMainSection: false },
  { id: "307.8", code: "307.8", title: "Multiple Hazards.", isMainSection: false },

  { id: "308", code: "308", title: "Institutional Group I", isMainSection: true },
  { id: "308.1", code: "308.1", title: "Institutional Group I.", isMainSection: false },
  { id: "308.2", code: "308.2", title: "Institutional Group I-1.", isMainSection: false },
  { id: "308.2.1", code: "308.2.1", title: "Condition 1.", isMainSection: false },
  { id: "308.2.2", code: "308.2.2", title: "Condition 2.", isMainSection: false },
  { id: "308.2.3", code: "308.2.3", title: "Six to 16 Persons Receiving Custodial Care.", isMainSection: false },
  { id: "308.2.4", code: "308.2.4", title: "Five or Fewer Persons Receiving Custodial Care.", isMainSection: false },
  { id: "308.3", code: "308.3", title: "Institutional Group I-2.", isMainSection: false },
  { id: "308.3.1", code: "308.3.1", title: "Occupancy Conditions.", isMainSection: false },
  { id: "308.3.1.1", code: "308.3.1.1", title: "Condition 1.", isMainSection: false },
  { id: "308.3.1.2", code: "308.3.1.2", title: "Condition 2.", isMainSection: false },
  { id: "308.3.2", code: "308.3.2", title: "Five or Fewer Persons Receiving Medical Care.", isMainSection: false },
  { id: "308.4", code: "308.4", title: "Institutional Group I-3.", isMainSection: false },
  { id: "308.4.1", code: "308.4.1", title: "Condition 1.", isMainSection: false },
  { id: "308.4.2", code: "308.4.2", title: "Condition 2.", isMainSection: false },
  { id: "308.4.3", code: "308.4.3", title: "Condition 3.", isMainSection: false },
  { id: "308.4.4", code: "308.4.4", title: "Condition 4.", isMainSection: false },
  { id: "308.4.5", code: "308.4.5", title: "Condition 5.", isMainSection: false },
  { id: "308.5", code: "308.5", title: "Institutional Group I-4, Day Care Facilities.", isMainSection: false },
  { id: "308.5.1", code: "308.5.1", title: "Classification as Group E.", isMainSection: false },
  { id: "308.5.2", code: "308.5.2", title: "Within a Place of Religious Worship.", isMainSection: false },
  { id: "308.5.3", code: "308.5.3", title: "Five or Fewer Persons Receiving Care.", isMainSection: false },
  { id: "308.5.4", code: "308.5.4", title: "Five or Fewer Persons Receiving Care in a Dwelling Unit.", isMainSection: false },

  { id: "309", code: "309", title: "Mercantile Group M", isMainSection: true },
  { id: "309.1", code: "309.1", title: "Mercantile Group M.", isMainSection: false },
  { id: "309.2", code: "309.2", title: "Quantity of Hazardous Materials.", isMainSection: false },
  { id: "309.3", code: "309.3", title: "Motor Fuel-Dispensing Facilities.", isMainSection: false },

  { id: "310", code: "310", title: "Residential Group R", isMainSection: true },
  { id: "310.1", code: "310.1", title: "Residential Group R.", isMainSection: false },
  { id: "310.2", code: "310.2", title: "Residential Group R-1.", isMainSection: false },
  { id: "310.3", code: "310.3", title: "Residential Group R-2.", isMainSection: false },
  { id: "310.4", code: "310.4", title: "Residential Group R-3.", isMainSection: false },
  { id: "310.4.1", code: "310.4.1", title: "Care Facilities Within a Dwelling.", isMainSection: false },
  { id: "310.4.2", code: "310.4.2", title: "Lodging Houses.", isMainSection: false },
  { id: "310.5", code: "310.5", title: "Residential Group R-4.", isMainSection: false },
  { id: "310.5.1", code: "310.5.1", title: "Condition 1.", isMainSection: false },
  { id: "310.5.2", code: "310.5.2", title: "Condition 2.", isMainSection: false },

  { id: "311", code: "311", title: "Storage Group S", isMainSection: true },
  { id: "311.1", code: "311.1", title: "Storage Group S.", isMainSection: false },
  { id: "311.1.1", code: "311.1.1", title: "Accessory Storage Spaces.", isMainSection: false },
  { id: "311.1.2", code: "311.1.2", title: "Combustible Storage.", isMainSection: false },
  { id: "311.2", code: "311.2", title: "Moderate-Hazard Storage, Group S-1.", isMainSection: false },
  { id: "311.2.1", code: "311.2.1", title: "Aircraft Hangers.", isMainSection: false },
  { id: "311.2.2", code: "311.2.2", title: "Motor Vehicle Repair Garages.", isMainSection: false },
  { id: "311.3", code: "311.3", title: "Low-Hazard Storage, Group S-2.", isMainSection: false },
  { id: "311.3.1", code: "311.3.1", title: "Public Parking Garages.", isMainSection: false },

  { id: "312", code: "312", title: "Utility and Miscellaneous Group U", isMainSection: true },
  { id: "312.1", code: "312.1", title: "General.", isMainSection: false },
  { id: "312.1.1", code: "312.1.1", title: "Greenhouses.", isMainSection: false },
  { id: "312.2", code: "312.2", title: "Private Garages and Carports.", isMainSection: false },
  { id: "312.3", code: "312.3", title: "Residential Aircraft Hangars.", isMainSection: false },
];