import { ChecklistRowDef } from "@/lib/types";

export const ch5Rows: ChecklistRowDef[] = [
  { id: "ch5-title", code: "", title: "General Building Heights and Areas", isMainSection: false },
  { id: "501", code: "501", title: "General", isMainSection: true },
  { id: "501.1", code: "501.1", title: "Scope", isMainSection: false },
  { id: "502", code: "502", title: "Building Address", isMainSection: true },
  { id: "502.1", code: "502.1", title: "Address Identification", isMainSection: false },
  { id: "503", code: "503", title: "General Building Height and Area Limitations", isMainSection: true },
  { id: "503.1", code: "503.1", title: "General", isMainSection: false },
  { id: "503.1.1", code: "503.1.1", title: "Special Industrial Occupancies", isMainSection: false },
  { id: "503.1.2", code: "503.1.2", title: "Buildings on Same Lot", isMainSection: false },
  { id: "503.1.3", code: "503.1.3", title: "Type I Construction", isMainSection: false },
  { id: "503.1.4", code: "503.1.4", title: "Occupiable Roofs", isMainSection: false },
  { id: "503.1.4.1", code: "503.1.4.1", title: "Enclosures Over Occupiable Roof Areas", isMainSection: false },
  { id: "504", code: "504", title: "Building Height and Number of Stories", isMainSection: true },
  { id: "504.1", code: "504.1", title: "General", isMainSection: false },
  { id: "504.1.1", code: "504.1.1", title: "Unlimited Area Buildings", isMainSection: false },
  { id: "504.1.2", code: "504.1.2", title: "Special Provisions", isMainSection: false },
  { id: "504.2", code: "504.2", title: "Mixed Occupancy", isMainSection: false },
  { id: "504.3", code: "504.3", title: "Height in Feet", isMainSection: false },
  { id: "504.4", code: "504.4", title: "Number of Stories", isMainSection: false },
  { id: "505", code: "505", title: "Mezzanines and Equipment Platforms", isMainSection: true },
  { id: "505.1", code: "505.1", title: "General", isMainSection: false },
  { id: "505.2", code: "505.2", title: "Mezzanines", isMainSection: false },
  { id: "505.2.1", code: "505.2.1", title: "Area Limitation", isMainSection: false },
  { id: "505.2.1.1", code: "505.2.1.1", title: "Aggregate Area of Mezzanines and Equipment Platforms", isMainSection: false },
  { id: "505.2.2", code: "505.2.2", title: "Means of Egress", isMainSection: false },
  { id: "505.2.3", code: "505.2.3", title: "Openness", isMainSection: false },
  { id: "505.3", code: "505.3", title: "Equipment Platforms", isMainSection: false },
  { id: "505.3.1", code: "505.3.1", title: "Area Limitation", isMainSection: false },
  { id: "505.3.2", code: "505.3.2", title: "Automatic Sprinkler System", isMainSection: false },
  { id: "505.3.3", code: "505.3.3", title: "Guards", isMainSection: false },
  { id: "506", code: "506", title: "Building Area", isMainSection: true },
  { id: "506.1", code: "506.1", title: "General", isMainSection: false },
  { id: "506.1.1", code: "506.1.1", title: "Unlimited Area Buildings", isMainSection: false },
  { id: "506.1.2", code: "506.1.2", title: "Special Provisions", isMainSection: false },
  { id: "506.1.3", code: "506.1.3", title: "Basements", isMainSection: false },
  { id: "506.2", code: "506.2", title: "Allowable Area Determination", isMainSection: false },
  { id: "506.2.1", code: "506.2.1", title: "Single-Occupancy Buildings", isMainSection: false },
  { id: "506.2.2", code: "506.2.2", title: "Mixed-Occupancy Buildings", isMainSection: false },
  { id: "506.2.2.1", code: "506.2.2.1", title: "Group H-2 or H-3 Mixed Occupancies", isMainSection: false },
  { id: "506.3", code: "506.3", title: "Frontage Increase", isMainSection: false },
  { id: "506.3.1", code: "506.3.1", title: "Minimum Percentage of Perimeter", isMainSection: false },
  { id: "506.3.2", code: "506.3.2", title: "Minimum Frontage Distance", isMainSection: false },
  { id: "506.3.3", code: "506.3.3", title: "Amount of Increase", isMainSection: false },
  { id: "506.3.3.1", code: "506.3.3.1", title: "Section 507 Buildings", isMainSection: false },
  { id: "507", code: "507", title: "Unlimited Area Buildings", isMainSection: true },
  { id: "507.1", code: "507.1", title: "General", isMainSection: false },
  { id: "507.1.1", code: "507.1.1", title: "Accessory Occupancies", isMainSection: false },
  { id: "507.2", code: "507.2", title: "Measurement of Open Spaces", isMainSection: false },
  { id: "507.2.1", code: "507.2.1", title: "Reduced Open Space", isMainSection: false },
  { id: "507.3", code: "507.3", title: "Nonsprinklered, One-Story Buildings", isMainSection: false },
  { id: "507.4", code: "507.4", title: "Sprinklered, One-Story Buildings", isMainSection: false },
  { id: "507.4.1", code: "507.4.1", title: "Mixed Occupancy Buildings with Groups A-1 and A-2", isMainSection: false },
  { id: "507.5", code: "507.5", title: "Two-Story Buildings", isMainSection: false },
  { id: "507.6", code: "507.6", title: "Group A-3 Buildings of Type II Construction", isMainSection: false },
  { id: "507.7", code: "507.7", title: "Group A-3 Buildings of Type III and IV Construction", isMainSection: false },
  { id: "507.8", code: "507.8", title: "Group H-2, H-3 and H-4 Occupancies", isMainSection: false },
  { id: "507.8.1", code: "507.8.1", title: "Allowable Area", isMainSection: false },
  { id: "507.8.1.1", code: "507.8.1.1", title: "Located Within the Building", isMainSection: false },
  { id: "507.8.1.1.1", code: "507.8.1.1.1", title: "Rooms for Flammable or Combustible Liquid Use, Dispensing or Mixing in Open Systems", isMainSection: false },
  { id: "507.8.1.1.2", code: "507.8.1.1.2", title: "Liquid Storage Rooms and Rooms for Flammable or Combustible Liquid Use in Closed Systems", isMainSection: false },
  { id: "507.8.1.1.3", code: "507.8.1.1.3", title: "Spray Paint Booths", isMainSection: false },
  { id: "507.8.2", code: "507.8.2", title: "Located on Building Perimeter", isMainSection: false },
  { id: "507.8.3", code: "507.8.3", title: "Occupancy Separations", isMainSection: false },
  { id: "507.8.4", code: "507.8.4", title: "Height Limitations", isMainSection: false },
  { id: "507.9", code: "507.9", title: "Unlimited Mixed Occupancy Buildings with Group H-5", isMainSection: false },
  { id: "507.10", code: "507.10", title: "Aircraft Paint Hangar", isMainSection: false },
  { id: "507.11", code: "507.11", title: "Group E Buildings", isMainSection: false },
  { id: "507.12", code: "507.12", title: "Motion Picture Theaters", isMainSection: false },
  { id: "507.13", code: "507.13", title: "Covered and Open Mall Buildings and Anchor Buildings", isMainSection: false },
  { id: "508", code: "508", title: "Mixed Use and Occupancy", isMainSection: true },
  { id: "508.1", code: "508.1", title: "General", isMainSection: false },
  { id: "508.2", code: "508.2", title: "Accessory Occupancies", isMainSection: false },
  { id: "508.2.1", code: "508.2.1", title: "Occupancy Classification", isMainSection: false },
  { id: "508.2.2", code: "508.2.2", title: "Allowable Building Height", isMainSection: false },
  { id: "508.2.3", code: "508.2.3", title: "Allowable Building Area", isMainSection: false },
  { id: "508.2.4", code: "508.2.4", title: "Separation of Occupancies", isMainSection: false },
  { id: "508.3", code: "508.3", title: "Nonseparated Occupancies", isMainSection: false },
  { id: "508.3.1", code: "508.3.1", title: "Occupancy Classification", isMainSection: false },
  { id: "508.3.1.1", code: "508.3.1.1", title: "High-Rise Buildings", isMainSection: false },
  { id: "508.3.1.2", code: "508.3.1.2", title: "Group I-2, Condition 2 Occupancies", isMainSection: false },
  { id: "508.3.2", code: "508.3.2", title: "Allowable Building Area, Height and Number of Stories", isMainSection: false },
  { id: "508.3.3", code: "508.3.3", title: "Separation", isMainSection: false },
  { id: "508.4", code: "508.4", title: "Separated Occupancies", isMainSection: false },
  { id: "508.4.1", code: "508.4.1", title: "Occupancy Classification", isMainSection: false },
  { id: "508.4.2", code: "508.4.2", title: "Allowable Building Area", isMainSection: false },
  { id: "508.4.3", code: "508.4.3", title: "Allowable Building Height and Number of Stories", isMainSection: false },
  { id: "508.4.4", code: "508.4.4", title: "Separation", isMainSection: false },
  { id: "508.4.4.1", code: "508.4.4.1", title: "Construction", isMainSection: false },
  { id: "508.5", code: "508.5", title: "Live/Work Units", isMainSection: false },
  { id: "508.5.1", code: "508.5.1", title: "Limitations", isMainSection: false },
  { id: "508.5.2", code: "508.5.2", title: "Occupancies", isMainSection: false },
  { id: "508.5.3", code: "508.5.3", title: "Means of Egress", isMainSection: false },
  { id: "508.5.4", code: "508.5.4", title: "Egress Capacity", isMainSection: false },
  { id: "508.5.5", code: "508.5.5", title: "Spiral Stairways", isMainSection: false },
  { id: "508.5.6", code: "508.5.6", title: "Vertical Openings", isMainSection: false },
  { id: "508.5.7", code: "508.5.7", title: "Fire Protection", isMainSection: false },
  { id: "508.5.8", code: "508.5.8", title: "Structural", isMainSection: false },
  { id: "508.5.9", code: "508.5.9", title: "Accessibility", isMainSection: false },
  { id: "508.5.10", code: "508.5.10", title: "Ventilation", isMainSection: false },
  { id: "508.5.11", code: "508.5.11", title: "Plumbing Facilities", isMainSection: false },
  { id: "509", code: "509", title: "Incidental Uses", isMainSection: true },
  { id: "509.1", code: "509.1", title: "General", isMainSection: false },
  { id: "509.2", code: "509.2", title: "Occupancy Classification", isMainSection: false },
  { id: "509.3", code: "509.3", title: "Area Limitations", isMainSection: false },
  { id: "509.4", code: "509.4", title: "Separation and Protection", isMainSection: false },
  { id: "509.4.1", code: "509.4.1", title: "Separation", isMainSection: false },
  { id: "509.4.1.1", code: "509.4.1.1", title: "Type IV-B and IV-C Construction", isMainSection: false },
  { id: "509.4.2", code: "509.4.2", title: "Protection", isMainSection: false },
  { id: "509.4.2.1", code: "509.4.2.1", title: "Protection Limitation", isMainSection: false },
  { id: "510", code: "510", title: "Special Provisions", isMainSection: true },
  { id: "510.1", code: "510.1", title: "General", isMainSection: false },
  { id: "510.2", code: "510.2", title: "Horizontal Building Separation Allowance", isMainSection: false },
  { id: "510.3", code: "510.3", title: "Group S-2 Enclosed Parking Garage with Group S-2 Open Parking Garage Above", isMainSection: false },
  { id: "510.4", code: "510.4", title: "Parking Beneath Group R", isMainSection: false },
  { id: "510.5", code: "510.5", title: "Group R-1 and R-2 Buildings of Type IIIA Construction", isMainSection: false },
  { id: "510.6", code: "510.6", title: "Group R-1 and R-2 Buildings of Type IIA Construction", isMainSection: false },
  { id: "510.7", code: "510.7", title: "Open Parking Garage Beneath Groups A, I, B, M and R", isMainSection: false },
  { id: "510.7.1", code: "510.7.1", title: "Fire Separation", isMainSection: false },
  { id: "510.8", code: "510.8", title: "Group B or M Buildings with Group S-2 Open Parking Garage Above", isMainSection: false },
  { id: "510.9", code: "510.9", title: "Multiple Buildings Above a Horizontal Assembly", isMainSection: false },
];